
# This is a bash script to display the system informaion.

on:
  push:
    branches:
        - main 

jobs:
  test:
    runs-on: ubuntu-lates


    steps:
      - name: Checkout repository
        users: actions/checkout@v2

      - name: Run System Information Scrip
        run: systeminfo.sh

