name: Bash Script Test

on:
  push:
    branches:
      - main

jobs:
  systeminfo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run System Info Script
        run: bash systeminfo.sh


        