
Hello this is my first my Github Action

on:
  push:
    branches:
      -main

Jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      -name: say hello
       run: echo "Hello from github action!"

