# Script Information

on:
  push:
    branches:
      - main


jobs:
  details: check git version
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: run below script
        run: bash assetdetails.sh