name: Asset Details Automation

on:
  push:
    branches:
      - main

jobs:
  Asset_Details:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        run: bash assetdetails.sh 

    
